apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: tp2_sysops 
spec:
  replicas: 2 
  selector: 
    matchLabels: 
      app: tp2_sysops 
  template:
  metadata: 
    labels: 
      app: tp2_sysops
  spec: 
    containers: 
    - name: tp2_sysops
      image: geoffrais/tp2_sysops:latest 
      ports: 
      - containerPort: 3000
