name: CI/CD Pipeline 

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest 
  
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Install dependencies
        run: npm install 
  
      - name: Run tests
        run: npm test 
        
      - name: Build Docker image
        run: docker build -t geoffrais/tp2_sysops:latest .

      - name: Debug - List Docker images
        run: docker images  # Vérifier les images présentes

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
    
      - name: Push Docker image
        run: docker push
