name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t geoffrais/tp2_sysops .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push geoffrais/tp2_sysops:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: List files in the repository  # Débogage pour vérifier les fichiers
        run: |
          ls -R
      
      - name: Trouver le chemin du dossier contenant deployment.yaml
        run: |
          file_path=$(find $GITHUB_WORKSPACE -name "index.js")
          if [ -z "$file_path" ]; then
            echo "Error: index.js introuvable !"
            exit 1
          else
            dir_path=$(dirname "$file_path")
            echo "Le fichier deployment.yaml se trouve dans : $dir_path"
            echo "DEPLOYMENT_PATH=$dir_path" >> $GITHUB_ENV
          fi


      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f $GITHUB_WORKSPACE/deployment.yaml
          kubectl apply -f service.yaml
